### PR TITLE
Feedback: Add chapter about feedback

### PR DESCRIPTION
**Pull request by MarkusAbtion**
This chapter tries to describe what feedback is, how to give it, and when to give it - all in an Abtion context.

### CODE REVIEW

**Comment by KlausEnevoldsen-Abtion** [comment]
Very nice - is a chapter without a reference to Kanye West even a chapter? 🥇

**Review by hcarreras — APPROVED** [review]
👏👏👏

Very extensible - not everyone will read it - but very well written.
I believe a Smart Tuesday would be a good addition (to the presentation you made for Tech Leads and EMs). That way, everyone will be aware that this is here.

**Comment by hcarreras** [comment]
I specifically like the Randical Candor Matrix. It was new to me and It made me reflect.

**Comment by hcarreras** [comment]
I did not know the reference: https://www.youtube.com/watch?v=RvaakT52RjQ
Quite funny 🤪

**Pull request merged**
