### PR TITLE
Add median experience to SE career ladder

### PR DESCRIPTION
**Pull request by hcarreras**
After many inquiries on the topic, I've studied the historical median at Abtion on different levels. Although experience is a sensitive topic, I believe it can help to set expectations.
This does not change the fact that people are evaluated on skills.

### CODE REVIEW

**Comment by hcarreras** [comment]
To be announced in this week's newsletter

**Review by jeppester — APPROVED** [review]
👍

**Review by DeWinther — APPROVED** [review]
Looks good!

**Comment by hcarreras** [comment]
Feedback is still welcome

**Pull request merged**
